version: '3.1'
services:
  
  minio1:
    image: minio/minio:latest
    restart: always
    command: server --console-address ":9001" http://minio1/data1 http://minio1/data2 http://minio1/data3 http://minio1/data4
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: 
      MINIO_ACCESS_KEY: 
      MINIO_SECRET_KEY: 
      MINIO_BROWSER_REDIRECT_URL: https://console-minio-backup.example.com/
    volumes:
      - /Backup/minio/data1-1:/data1
      - /Backup/minio/data1-2:/data2
      - /Backup/minio/data1-3:/data3
      - /Backup/minio/data1-4:/data4
